apiVersion: v1
kind: Secret
metadata:
  name: sqlsecret
  namespace: api
type: Opaque
data:
  SQL_USER: c3FsYWRtaW5yS20wNjU4
  SQL_PASSWORD: cVQzdGQ3RG84
  SQL_SERVER: c3Fsc2VydmVycmttMDY1OC5kYXRhYmFzZS53aW5kb3dzLm5ldA==
  SQL_DBNAME: bXlkcml2aW5nREI=