kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-limited-access
  namespace: api
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["services", "endpoints", "pods","deployments","replicasets"]
  verbs: ["get", "list", "watch"] 