apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-deployment
  namespace: api
  labels:
    deploy: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - image: "registrycfl5818.azurecr.io/tripinsights/trips:1.0"
        imagePullPolicy: Always
        name: trips
        livenessProbe:
          httpGet:
            path: /api/trips/healthcheck
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/trips/healthcheck
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
        volumeMounts:
        - name: keyvault
          mountPath: /secrets
          readOnly: true
      volumes:
      - name: keyvault
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds
          options:
            keyvaultname: "vault1-hacker66-ea"
            keyvaultobjectnames: "username;password;sqlserver"
            keyvaultobjecttypes: "secret;secret;secret"
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER"
            resourcegroup: "teamResources"
            subscriptionid: "940a4437-eda8-4921-b571-320b4daed23d"
            tenantid: "17d9665a-11eb-4ef1-a76f-996b76dfdb78"
---
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: trips
  ports:
    - protocol: TCP
      name: trips-http
      port: 80
      targetPort: 80
    - protocol: TCP
      name: trips-https
      port: 443
      targetPort: 443
