apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-dev
  namespace: web
roleRef:
  kind: ClusterRole
  name: full-ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "7f63ff51-3ae5-40ee-bfbf-f373ac279fe5"
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-dev
  namespace: api
roleRef:
  kind: ClusterRole
  name: readonly-ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: Group
  name: "7f63ff51-3ae5-40ee-bfbf-f373ac279fe5"
  apiGroup: rbac.authorization.k8s.io